server:
  port: 8081

spring:
  application:
    name: dinnerfortwo
  datasource:
    url: jdbc:h2:file:~/dinner-prod-db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema-generate: create-drop
    dialect: H2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  swagger-ui:
    path: /swagger-ui.html
debug: true